Don't recreate `sdist-vX/.git` if it already exists
Step 1 of N for readonly cache support. Moves the error message for LLM sandboxes from `sdist-vX/.git` to:

```
error: Could not acquire lock
    Caused by: Could not create temporary file
    Caused by: Read-only file system (os error 30  at path "/home/konsti/.cache/uv/.tmpfvc4gV"
```